name = "custom-set"
version = "0.1.0"
defaultTargets = ["CustomSetTest"]
testDriver = "CustomSetTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "CustomSet"

[[lean_exe]]
name = "CustomSetTest"
root = "CustomSetTest"
