name = "queen-attack"
version = "0.1.0"
defaultTargets = ["QueenAttackTest"]
testDriver = "QueenAttackTest"
moreLeanArgs = [ "-DwarningAsError=true" ]

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "QueenAttack"

[[lean_lib]]
name = "Extra"

[[lean_exe]]
name = "QueenAttackTest"
root = "QueenAttackTest"
