name = "alphametics"
version = "0.1.0"
defaultTargets = ["AlphameticsTest"]
testDriver = "AlphameticsTest"
moreLeanArgs = [ "-DwarningAsError=true" ]

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Alphametics"

[[lean_lib]]
name = "Extra"

[[lean_exe]]
name = "AlphameticsTest"
root = "AlphameticsTest"
