name = "pascals-triangle"
version = "0.1.0"
defaultTargets = ["PascalsTriangleTest"]
testDriver = "PascalsTriangleTest"
moreLeanArgs = [ "-DwarningAsError=true" ]

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "PascalsTriangle"

[[lean_lib]]
name = "Extra"

[[lean_exe]]
name = "PascalsTriangleTest"
root = "PascalsTriangleTest"
