name = "bob"
version = "0.1.0"
defaultTargets = ["BobTest"]
testDriver = "BobTest"
moreLeanArgs = [ "-DwarningAsError=true" ]

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Bob"

[[lean_lib]]
name = "Extra"

[[lean_exe]]
name = "BobTest"
root = "BobTest"
